import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import StoreProvider from "@/components/StoreProvider";
import AppProvider from "@/components/AppProvider";
import "@ant-design/v5-patch-for-react-19";
import { Toaster } from "react-hot-toast";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "EZ Gadgets POS by Zagle.ai",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.className} antialiased`}>
        <StoreProvider>
          <AppProvider>
            {children}
            <Toaster />
          </AppProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
